### ISSUE TITLE
[semver:patch] PIPELINE_ID is now an envar!

### ISSUE THREAD

**Issue by eddiewebb** [eddiewebb/circleci-queue#125]
### Orb version
we can drop need for https://github.com/eddiewebb/circleci-queue/blob/main/src/%40orb.yml#L56 and just use `CIRCLE_PIPELINE_ID`

**Comment by sdarwin** [comment]
Hi,

Thanks for the orb!

Don't know if this issue is connected to this line of the config or not:

`my-pipeline: <<pipeline.number>>`

But as someone who doesn't program CircleCI often, I think the documentation could benefit from a comment because I was wondering "how do I know my pipeline number?"

```
# you don't need to discover this value. Literally write the 'template' variable <<pipeline.number>>
my-pipeline: <<pipeline.number>> 
```

**Comment by eddiewebb** [comment]
My basd, while ID is an envvar, NUMBER is still parameter only.
