### ISSUE TITLE
Script should avoid using two different versions of CircleCI's API

### ISSUE THREAD

**Issue by jaylattice** [eddiewebb/circleci-queue#58]
### Orb version

1.5.0

### What happened

Script uses two different versions of CircleCI's API (v1.1 and v2). I am not sure if we're using two different APIs because of a lack of feature parity between them... But if there is feature parity for this orb's intents and purposes, we should use a single API!

### Expected behavior

We should be using one API in the script to avoid potential API token bugs where the supplied API token is invalid for one API version but valid for another API version.

### How to fix

Make sure either the personal token or project token works on both APIs, then just use that API.

**Comment by jaylattice** [comment]
I suspect this is why we were running into issues with our project token (as v2 API does not support project tokens for some reason).

**Comment by eddiewebb** [comment]
1) Yes, you're right, it should
2) Yes, you're right, it is because feature parity is lacking
3) Yes, you're right, it is an issue for project tokens (which dont work on v2)

The need for v2 added timing and ordering at workflow level not available in v1, so in order to support, it must.  I will campaign for project token support in V2!

(I'll leave #48 open to track this need)
